GUI_config:
  online_phon_input: True
  main_panel:
    name_window: "TTS"
    add_audio_infos: True
    add_GST_infos: False
    add_play_button: False
    # width: 800
    width: 440
    height: 800
    input_width: 30
    control_width: 440
    control_height: 400
  add_keyboard: True
  detach_keyboard: False
  keyboard_options:
    name_window: "Keyboard"
    keys: "Emmanuelle"
    show_entry: False
    play_phone: False
    font_size: 12
    width: 350
    height: 250
    key_margin_x: 5  # Horizontal padding between keys
    key_margin_y: 5  # Vertical padding between keys
    max_button_width: 3 # Maximum button width (affects how wide the keyboard can get)

default_start_punctuation: "."
default_end_punctuation: "."
use_denoiser: True
visual_smoothing:
  activate: True
  cutoff: 5
subtitles:
  create_file: True
  duration_by_frame: 
    sampling_rate: 22050
    hop_length: 256
  max_nbr_char: 60

tts_models:
  - label: "Multi Speaker/Style"
    load_script: "load_fastspeech2"
    syn_script: "syn_fastspeech2"
    gui_script: "gui_fastspeech2"
    folder: "FastSpeech2"
    checkpoint_file: "390000"
    output_location: "output/audio"
    gst_token_list: {
        "COLERE": 1.0,
        "DESOLE": 1.0,
        "DETERMINE": 1.0,
        "ENTHOUSIASTE": 1.0,
        "ESPIEGLE": 1.0,
        "ETONNE": 1.0,
        "EVIDENCE": 1.0,
        "INCREDULE": 1.0,
        "NEUTRE": 1.0,
        "PENSIF": 1.0,
        "RECONFORTANT": 1.0,
        "SUPPLIANT": 1.0,
        "TOKEN13": 1.0,
        "TOKEN14": 1.0,
        "TOKEN15": 1.0,
        "TOKEN16": 1.0,
    }
    gui_control_bias: False
    gui_style_control: True
    gui_styleTag_control: False
    default_args:
      text_cleaners: ["basic_cleaners"]
      preprocess_config: "config/ALL_corpus/preprocess.yaml"
      model_config: "config/ALL_corpus/model.yaml"
      train_config: "config/ALL_corpus/train.yaml"
      vocoder: None
      speaker_id: 4
      mode: "single"
      pitch_control: 0.0
      energy_control: 0.0
      duration_control: 1.1
      duration_control_bias: 1.0
      pitch_control_bias: 0.0
      f1_control_bias: 0.0
      f2_control_bias: 0.0
      f3_control_bias: 0.0
      spectral_tilt_control_bias: 0.0
      energy_control_bias: 0.0
      relative_pos_control_bias: 0.0
      pfitzinger_control_bias: 0.0
      cog_control_bias: 0.0
      sb1k_control_bias: 0.0
      pause_control_bias: 0.0
      liaison_control_bias: 0.0
      silence_control_bias: False
      gst_token_index: 8
      style_intensity: 1.0
      enforce_linking_duration: True

vocoder_models:
  - label: "Hifi-GAN V2 FR 570000"
    load_script: "load_hifigan"
    syn_script: "syn_hifigan"
    folder: "hifi-gan-master"
    checkpoint_file: "FR_V2/g_00570000"
    config_path: "FR_V2/config.json"
    output_location: "./"

  # - label: "Waveglow NEB"
  #   load_script: "load_waveglow"
  #   syn_script: "syn_waveglow"
  #   folder: "Waveglow"
  #   checkpoint_file: "waveglow_NEB.pt"
  #   output_location: "./"
  #   default_args:
  #     filelist_path: "fastspeech2.txt"
  #     sigma: 0.6
  #     sampling_rate: 22050
  #     is_fp16: False
  #     denoiser_strengh: 0.0
  #     speed_factor: 1.0
  #     gain: 0.0
  #     negative_gain: 0.0